"""Leaderboard generator — static HTML + JSON output."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from repoeval.core.models import BenchmarkRun, LeaderboardEntry

LEADERBOARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }} — RepoEval Leaderboard</title>
<style>
:root { --bg: #0a0a0f; --card: #12121a; --border: #1e1e2e; --text: #e0e0e0; --dim: #666; --accent: #f97316; --green: #22c55e; --red: #ef4444; }
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
.container { max-width: 900px; margin: 0 auto; padding: 2rem 1rem; }
h1 { font-size: 2rem; margin-bottom: 0.5rem; }
.subtitle { color: var(--dim); margin-bottom: 2rem; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
.stat { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }
.stat-value { font-size: 1.5rem; font-weight: bold; color: var(--accent); }
.stat-label { font-size: 0.8rem; color: var(--dim); }
table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; }
th { background: var(--border); padding: 0.75rem 1rem; text-align: left; font-size: 0.8rem; text-transform: uppercase; color: var(--dim); }
td { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }
tr:hover { background: rgba(249,115,22,0.05); }
.pass { color: var(--green); }
.fail { color: var(--red); }
.badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; background: var(--border); }
.footer { margin-top: 2rem; text-align: center; color: var(--dim); font-size: 0.8rem; }
</style>
</head>
<body>
<div class="container">
<h1>🏆 {{ title }}</h1>
<p class="subtitle">Generated by <a href="https://github.com/EmbrOS-Experimental/repoeval" style="color:var(--accent)">RepoEval</a> · {{ timestamp }}</p>

<div class="stats">
  <div class="stat"><div class="stat-value">{{ total_tasks }}</div><div class="stat-label">Tasks</div></div>
  <div class="stat"><div class="stat-value" style="color:var(--green)">{{ passed }}</div><div class="stat-label">Passed</div></div>
  <div class="stat"><div class="stat-value" style="color:var(--red)">{{ failed }}</div><div class="stat-label">Failed</div></div>
  <div class="stat"><div class="stat-value">{{ "%.1f"|format(pass_rate * 100) }}%</div><div class="stat-label">Pass Rate</div></div>
  <div class="stat"><div class="stat-value">{{ "%.0f"|format(total_duration_ms / 1000) }}s</div><div class="stat-label">Duration</div></div>
  <div class="stat"><div class="stat-value">${{ "%.2f"|format(total_cost_usd) }}</div><div class="stat-label">Cost</div></div>
</div>

<h2 style="margin-bottom:1rem">Task Results</h2>
<table>
<thead><tr><th>#</th><th>Task</th><th>Status</th><th>Duration</th><th>Tests</th><th>Patch</th></tr></thead>
<tbody>
{% for r in results %}
<tr>
  <td>{{ loop.index }}</td>
  <td>{{ r.task.issue_title[:60] if r.task else r.task_id }}</td>
  <td class="{{ 'pass' if r.status.value == 'passed' else 'fail' }}">{{ r.status.value }}</td>
  <td>{{ "%.0f"|format(r.duration_ms / 1000) }}s</td>
  <td>{{ r.tests_passed }}/{{ r.tests_total }}</td>
  <td>{{ "✓" if r.patch_correct else "✗" if r.patch_correct is not none else "—" }}</td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="footer">
  Built by <a href="https://embros.xyz" style="color:var(--accent)">EmbrOS</a> · Apache-2.0 License
</div>
</div>
</body>
</html>
"""


class LeaderboardGenerator:
    """Generate static HTML leaderboard from benchmark results."""

    def generate(
        self,
        run: BenchmarkRun,
        output_dir: str | Path,
        title: Optional[str] = None,
    ) -> Path:
        """Generate HTML leaderboard and JSON results."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate HTML
        from jinja2 import Template
        template = Template(LEADERBOARD_HTML)
        html = template.render(
            title=title or run.name or f"Benchmark {run.id}",
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            total_tasks=run.total_tasks,
            passed=run.passed,
            failed=run.failed,
            pass_rate=run.pass_rate,
            total_duration_ms=run.total_duration_ms,
            total_cost_usd=run.total_cost_usd,
            results=run.results,
        )

        html_path = output_dir / "index.html"
        html_path.write_text(html, encoding="utf-8")

        # Generate JSON
        json_path = output_dir / "results.json"
        json_path.write_text(run.model_dump_json(indent=2), encoding="utf-8")

        return html_path

    def generate_comparison(
        self,
        runs: list[BenchmarkRun],
        output_dir: str | Path,
        title: str = "Comparison",
    ) -> Path:
        """Generate a comparison leaderboard for multiple runs."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        from jinja2 import Template

        comparison_html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }} — RepoEval Comparison</title>
<style>
:root { --bg: #0a0a0f; --card: #12121a; --border: #1e1e2e; --text: #e0e0e0; --dim: #666; --accent: #f97316; --green: #22c55e; --red: #ef4444; }
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
.container { max-width: 900px; margin: 0 auto; padding: 2rem 1rem; }
h1 { font-size: 2rem; margin-bottom: 0.5rem; }
table { width: 100%; border-collapse: collapse; background: var(--card); border-radius: 8px; overflow: hidden; margin-top: 1rem; }
th { background: var(--border); padding: 0.75rem 1rem; text-align: left; font-size: 0.8rem; text-transform: uppercase; color: var(--dim); }
td { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }
.pass { color: var(--green); }
.fail { color: var(--red); }
.footer { margin-top: 2rem; text-align: center; color: var(--dim); font-size: 0.8rem; }
</style>
</head>
<body>
<div class="container">
<h1>📊 {{ title }}</h1>
<p style="color:var(--dim)">Comparing {{ runs|length }} benchmark runs</p>
<table>
<thead><tr><th>Run</th><th>Agent</th><th>Model</th><th>Pass Rate</th><th>Passed</th><th>Duration</th><th>Cost</th></tr></thead>
<tbody>
{% for r in runs %}
<tr>
  <td>{{ r.name or r.id[:8] }}</td>
  <td><span class="badge">{{ r.agent_type }}</span></td>
  <td>{{ r.metadata.get('model', 'unknown') }}</td>
  <td class="{{ 'pass' if r.pass_rate >= 0.5 else 'fail' }}">{{ "%.1f"|format(r.pass_rate * 100) }}%</td>
  <td>{{ r.passed }}/{{ r.total_tasks }}</td>
  <td>{{ "%.0f"|format(r.total_duration_ms / 1000) }}s</td>
  <td>${{ "%.2f"|format(r.total_cost_usd) }}</td>
</tr>
{% endfor %}
</tbody>
</table>
<div class="footer">Built by <a href="https://embros.xyz" style="color:var(--accent)">EmbrOS</a></div>
</div>
</body>
</html>"""

        template = Template(comparison_html)
        html = template.render(title=title, runs=runs)

        html_path = output_dir / "comparison.html"
        html_path.write_text(html, encoding="utf-8")

        return html_path
